import { defineStore } from "pinia";

export const useProductsStore = defineStore("products", {
  state: () => ({
    buyProducts: [
      {
        id: 1,
        name: "Vestido Rojo",
        description: "Perfecto para fiestas",
        image: require("@/assets/images/vestido-rojo.jpg"),
        type: "Compra",
        price: 11.5,
      },
      {
        id: 2,
        name: "Vestido Azul",
        description: "Ideal para ocasiones formales",
        image: require("@/assets/images/vestido-azul.jpg"),
        type: "Compra",
        price: 23,
      },
      {
        id: 3,
        name: "Blusa Blanca",
        description: "Versátil y elegante",
        image: require("@/assets/images/blusa-blanca.jpg"),
        type: "Compra",
        price: 64,
      },
      {
        id: 4,
        name: "Falda Negra",
        description: "Un clásico imprescindible",
        image: require("@/assets/images/falda-negra.jpg"),
        type: "Compra",
        price: 34,
      },
      {
        id: 5,
        name: "Pantalón Beige",
        description: "Comodidad y estilo",
        image: require("@/assets/images/pantalon-beige.jpg"),
        type: "Compra",
        price: 12,
      },
      {
        id: 6,
        name: "Camisa Rayas",
        description: "Un look casual",
        image: require("@/assets/images/camisa-rayas.jpg"),
        type: "Compra",
        price: 5,
      },
      {
        id: 7,
        name: "Chaqueta Marrón",
        description: "Perfecta para otoño",
        image: require("@/assets/images/chaqueta-marron.jpg"),
        type: "Compra",
        price: 16,
      },
      {
        id: 8,
        name: "Blusa Floral",
        description: "Fresca y primaveral",
        image: require("@/assets/images/blusa-floral.jpg"),
        type: "Compra",
        price: 23,
      },
      {
        id: 9,
        name: "Zapatos Negros",
        description: "Elegancia asegurada",
        image: require("@/assets/images/zapatos-negros.jpg"),
        type: "Compra",
        price: 51,
      },
      {
        id: 10,
        name: "Bolso Beige",
        description: "Un complemento ideal",
        image: require("@/assets/images/bolso-beige.jpg"),
        type: "Compra",
        price: 19,
      },
      {
        id: 11,
        name: "Abrigo Largo",
        description: "Estilo invernal",
        image: require("@/assets/images/abrigo-largo.jpg"),
        type: "Compra",
        price: 19.99,
      },
      {
        id: 12,
        name: "Sombrero Fedora",
        description: "Un toque sofisticado",
        image: require("@/assets/images/sombrero-fedora.jpg"),
        type: "Compra",
        price: 11.5,
      },
    ],
    rentProducts: [
      {
        id: 13,
        name: "Vestido Dorado",
        description: "Ideal para galas",
        image: require("@/assets/images/vestido-dorado.jpg"),
        type: "Alquiler",
        price: 19.99,
      },
      {
        id: 14,
        name: "Vestido Verde",
        description: "Frescura natural",
        image: require("@/assets/images/vestido-verde.jpg"),
        type: "Alquiler",
        price: 34,
      },
      {
        id: 15,
        name: "Sombrero Fedora",
        description: "Un toque sofisticado",
        image: require("@/assets/images/sombrero-fedora.jpg"),
        type: "Alquiler",
        price: 23.98,
      },
      {
        id: 16,
        name: "Abrigo Largo",
        description: "Estilo invernal",
        image: require("@/assets/images/abrigo-largo.jpg"),
        type: "Alquiler",
        price: 31,
      },
      {
        id: 17,
        name: "Bolso Beige",
        description: "Un complemento ideal",
        image: require("@/assets/images/bolso-beige.jpg"),
        type: "Alquiler",
        price: 3,
      },
      {
        id: 18,
        name: "Blusa Floral",
        description: "Fresca y primaveral",
        image: require("@/assets/images/blusa-floral.jpg"),
        type: "Alquiler",
        price: 3,
      },
      {
        id: 19,
        name: "Camisa Rayas",
        description: "Un look casual",
        image: require("@/assets/images/camisa-rayas.jpg"),
        type: "Alquiler",
        price: 3,
      },
    ],
  }),
  getters: {
    getBuyProducts: (state) => state.buyProducts,
    getRentProducts: (state) => state.rentProducts,
  },
});
